import type { BrowserWindow } from 'electron';
import type { ScrapedTransaction } from './types';
export interface VisionConfig {
    provider: 'claude' | 'ollama' | 'none';
    apiKey?: string;
    model?: string;
    maxTokens?: number;
    ollamaEndpoint?: string;
    customPrompt?: string;
}
export declare const DEFAULT_CLAUDE_PROMPT = "You are analyzing a bank transaction page screenshot. Extract ONLY the visible posted transactions from this single viewport.\n\nWHAT TO LOOK FOR:\n- Transaction tables or lists showing financial activity\n- Columns typically include: Date, Description/Merchant, Amount, Balance, Category\n- Look for dollar amounts (positive or negative)\n- Look for dates in any format (Feb 04, 02/04/2024, etc.)\n- Look for merchant names or transaction descriptions\n- Look for category labels (Shopping, Groceries, Fast Food, Gas/Fuel, Auto & Transport, Bills & Utilities, etc.)\n\nCRITICAL RULES:\n1. Extract ONLY transactions visible in THIS screenshot (typically 10-50 recent transactions)\n2. Include ALL transactions - both posted/cleared AND pending/processing transactions\n3. For pending/processing transactions, ALWAYS use empty string \"\" for the category field\n4. For posted/cleared transactions, extract the category if visible, otherwise use empty string \"\"\n5. Clean merchant names (remove prefixes like \"ACH\", \"DEBIT\", \"POS\", \"CARD PURCHASE\", etc.)\n6. Use negative amounts for expenses (money going out)\n7. Use positive amounts for income (money coming in)\n8. Parse dates in any format you see (Month DD, YYYY or MM/DD/YYYY, etc.)\n9. If you see a balance column, include it\n\nIMPORTANT: If you cannot find ANY transaction data in the image:\n- Return an empty array: []\n- The page might be a login screen, loading screen, or error page\n- The page might not have finished loading transaction data yet\n\nReturn ONLY a JSON array with this exact structure (no markdown, no explanation):\n[\n  {\n    \"date\": \"Feb 04, 2026\",\n    \"description\": \"Shake Shack\",\n    \"amount\": \"-28.50\",\n    \"balance\": \"2380.52\",\n    \"category\": \"Fast Food\",\n    \"confidence\": 95\n  }\n]\n\nIf the bank shows a category for the transaction, extract it exactly as shown. If no category is visible, use an empty string \"\".\n\nExtract every visible transaction in the screenshot. Focus on the most recent transactions shown.";
export declare const DEFAULT_OLLAMA_PROMPT = "You are analyzing a bank transaction page screenshot. Extract ONLY the visible posted transactions.\n\nWHAT TO LOOK FOR:\n- Transaction tables with Date, Description/Merchant, Amount, Balance, Category columns\n- Dollar amounts (positive for income, negative for expenses)\n- Dates in any format\n- Merchant names or descriptions\n- Category labels (Shopping, Groceries, Fast Food, Gas/Fuel, etc.)\n\nCRITICAL RULES:\n1. Extract ONLY visible transactions in THIS screenshot\n2. Include ALL transactions - both posted/cleared AND pending/processing\n3. For pending/processing transactions, ALWAYS use empty string \"\" for category\n4. For posted/cleared transactions, extract category if visible, otherwise use empty string \"\"\n5. Clean merchant names (remove prefixes like \"ACH\", \"DEBIT\", \"POS\")\n6. Use negative amounts for expenses, positive for income\n\nReturn ONLY a JSON array with this structure (no markdown, no explanation):\n[\n  {\n    \"date\": \"Feb 04, 2026\",\n    \"description\": \"Shake Shack\",\n    \"amount\": \"-28.50\",\n    \"balance\": \"2380.52\",\n    \"category\": \"Fast Food\",\n    \"confidence\": 95\n  }\n]\n\nIf no transactions are found, return: []";
/**
 * Scrape transactions using AI vision capabilities (Claude or Ollama)
 * This is more resilient to website changes than DOM parsing
 */
export declare function scrapeWithVision(window: BrowserWindow, config: VisionConfig): Promise<ScrapedTransaction[]>;
